Update _build_openwrt.yaml

diff --git a/.github/workflows/_build_openwrt.yaml b/.github/workflows/_build_openwrt.yaml
--- a/.github/workflows/_build_openwrt.yaml
+++ b/.github/workflows/_build_openwrt.yaml
@@ -178,11 +178,11 @@ jobs:
         run: |
           ccache -p
           
-          make download -j$(nproc) || {
-            echo "Retrying..."
-            sleep 30
+          #make download -j$(nproc) || {
+            #echo "Retrying..."
+            #sleep 30
             make download -j1 V=s
-          }
+          #}
           make -j$(nproc) || {
             echo "Retrying..."
             sleep 30
