Update build-openwrt.yaml

diff --git a/.github/workflows/build-openwrt.yaml b/.github/workflows/build-openwrt.yaml
--- a/.github/workflows/build-openwrt.yaml
+++ b/.github/workflows/build-openwrt.yaml
@@ -16,6 +16,7 @@ env:
   REMOTE_REPOSITORY: pesa1234/openwrt
   CONFIG_FILE: mt6000.config
   GH_TOKEN: ${{ github.token }}
+  TARGET_REPOSITORY: "${{ github.repository }}"
 
 jobs:
   check_commits:
@@ -34,7 +35,7 @@ jobs:
           remote_branch=$(git ls-remote https://github.com/${{ env.REMOTE_REPOSITORY }}.git "refs/heads/next-*" | sed -e 's|\(.*heads/\)||' | grep -viE 'test|beta' | sort -V | tail -n1)
           [ -n "$remote_branch" ] && latest_commit_sha=$(gh api "repos/${{ env.REMOTE_REPOSITORY }}/commits/${remote_branch}" --jq .sha)
           [ -z "$latest_commit_sha" ] && { echo "*** COULD NOT GET latest_commit_sha FROM remote_branch=$remote_branch ***" ; exit 1; }
-          gh api "repos/${{ github.repository }}/releases/latest" --jq .body 2>/dev/null | grep -q "${latest_commit_sha}" && echo "new_commits=false" >> $GITHUB_OUTPUT || echo "new_commits=true" >> $GITHUB_OUTPUT
+          gh api "repos/$TARGET_REPOSITORY/releases/latest" --jq .body 2>/dev/null | grep -q "${latest_commit_sha}" && echo "new_commits=false" >> $GITHUB_OUTPUT || echo "new_commits=true" >> $GITHUB_OUTPUT
           echo "remote_branch=${remote_branch}"
           echo "release_prefix=${remote_branch%.rss*}"
           echo "latest_commit_sha=$latest_commit_sha"
@@ -86,7 +87,6 @@ jobs:
 
       - name: Setup configuration and custom files
         run: |
-          rm -frv builder_repo/.git builder_repo/.github
           mv -v ./builder_repo/${{ env.CONFIG_FILE }} .config
           mv -v ./builder_repo/files ./
           mv -v ./builder_repo/patches ./
@@ -95,11 +95,11 @@ jobs:
 
       - name: Build firmware
         run: |
-          make download -j$(nproc) || {
-            echo "Retrying..."
-            sleep 30
-            make download -j1 V=s
-          }
+          #make download -j$(nproc) || {
+            #echo "Retrying..."
+            #sleep 30
+          make download -j1 V=s
+          #}
           make -j$(nproc) || {
             echo "Retrying..."
             sleep 30
@@ -108,7 +108,7 @@ jobs:
           mkdir -p ./release
           find ./bin -type f \( -iname 'openwrt-*-sysupgrade.bin' -or -iname 'config.buildinfo' \) -exec cp -v {} ./release/ \; ||:
           mv .config release/full.config ||:
-          cd ./release && find -iname 'openwrt-*-sysupgrade.bin' -exec sh -c "sha256sum {} >sha256sums" \; ||:
+          cd ./release && find -type f -iname 'openwrt-*-sysupgrade.bin' -exec sh -c "sha256sum {} >sha256sums" \; ||:
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v6.0.0
@@ -116,27 +116,32 @@ jobs:
           name: gl-mt6000-firmware
           path: ./release/*
 
+      - name: Get release info
+        run: |
+          VERSION=$(find ./bin -type f -iname 'version.buildinfo' -print -quit | xargs -r cat | tr -d '\n')
+          TAG="$(date +%F)_$VERSION_${{ needs.check_commits.outputs.release_prefix }}"
+          echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
+          
       - name: Push build to repo
         run: |
+          export GIT_SSH_COMMAND="ssh -i ~/.ssh/github -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
           cd ./bin
           git init
-          git remote add origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
+          git remote add origin git@github.com:$TARGET_REPOSITORY.git
           git fetch origin main
           git checkout -B main origin/main
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
           git add .
-          git commit -m "Add firmware build $(date +'%Y-%m-%d %H:%M:%S')"
+          git commit -m "$RELEASE_TAG"
           git push origin main
 
       - name: Create release
         run: |
-          RELEASE_TAG="${{ needs.check_commits.outputs.release_prefix }}-$(date +%F)"
-          REPO="${{ github.repository }}"
-          if gh release view "$RELEASE_TAG" --repo "$REPO" >/dev/null 2>&1; then
-            gh release delete "$RELEASE_TAG" --cleanup-tag -y --repo "$REPO"
+          if gh release view "$RELEASE_TAG" --repo "$TARGET_REPOSITORY" >/dev/null 2>&1; then
+            gh release delete "$RELEASE_TAG" --cleanup-tag -y --repo "$TARGET_REPOSITORY"
           fi
-          gh release create "$RELEASE_TAG" --repo "$REPO" --latest --notes "### 🔄 Main Repository
+          gh release create "$RELEASE_TAG" --repo "$TARGET_REPOSITORY" --latest --notes "### 🔄 Main Repository
           - **Repository:** [${{ env.REMOTE_REPOSITORY }}](https://github.com/${{ env.REMOTE_REPOSITORY }})
           - **Branch:** ${{ needs.check_commits.outputs.remote_branch }}
           - **Commit:** ${{ needs.check_commits.outputs.latest_commit_sha }}
@@ -163,6 +168,6 @@ jobs:
 
       - name: Clean up old releases
         run: |
-          gh api repos/${{ github.repository }}/releases --paginate --jq '.[10:] | .[] | "\(.id) \(.tag_name)"' | while read id tag; do
-            gh api -X DELETE "repos/${{ github.repository }}/releases/$id" && gh api -X DELETE "repos/${{ github.repository }}/git/refs/tags/$tag" 2>/dev/null ||:
+          gh api repos/$TARGET_REPOSITORY/releases --paginate --jq '.[5:] | .[] | "\(.id) \(.tag_name)"' | while read id tag; do
+            gh api -X DELETE "repos/$TARGET_REPOSITORY/releases/$id" && gh api -X DELETE "repos/$TARGET_REPOSITORY/git/refs/tags/$tag" 2>/dev/null ||:
           done
