Update build-openwrt-self-hosted.yaml

diff --git a/.github/workflows/build-openwrt-self-hosted.yaml b/.github/workflows/build-openwrt-self-hosted.yaml
--- a/.github/workflows/build-openwrt-self-hosted.yaml
+++ b/.github/workflows/build-openwrt-self-hosted.yaml
@@ -84,11 +84,11 @@ jobs:
             sleep 30
             make download -j1 V=s
           }
-          make -j$(nproc) || {
-            echo "Retrying..."
-            sleep 30
-            make -j1 V=s
-          }
+          #make -j$(nproc) || {
+            #echo "Retrying..."
+            #sleep 30
+          make -j1 V=s
+          #}
           mkdir -p ./release
           find ./bin -type f \( -iname 'openwrt-*-sysupgrade.bin' -or -iname 'config.buildinfo' \) -exec cp -v {} ./release/ \; ||:
           mv .config release/full.config ||:
@@ -146,6 +146,6 @@ jobs:
 
       - name: Clean up old releases
         run: |
-          gh api repos/$TARGET_REPOSITORY/releases --paginate --jq '.[10:] | .[] | "\(.id) \(.tag_name)"' | while read id tag; do
+          gh api repos/$TARGET_REPOSITORY/releases --paginate --jq '.[5:] | .[] | "\(.id) \(.tag_name)"' | while read id tag; do
             gh api -X DELETE "repos/$TARGET_REPOSITORY/releases/$id" && gh api -X DELETE "repos/$TARGET_REPOSITORY/git/refs/tags/$tag" 2>/dev/null ||:
           done
